"""Pydantic v2 Schemas for Aivora Concierge Agent."""
from .auth import (
    ForgotPasswordRequest,
    SocialLoginRequest,
    Token,
    TokenPayload,
    UserCreate,
    UserLogin,
    UserPreferenceResponse,
    UserResponse,
)
from app.schemas.marketing import (
    InquiryCreate,
    InquiryResponse,
    MessageRequest,
    MessageResponse,
    PasswordResetResponse,
    SessionCreate,
    SessionResponse,
    StatsResponse,
    SubscriberCreate,
    SubscriberResponse,
    TaskExecuteRequest,
    TaskExecuteResponse,
    TaskStatusResponse,
    TokenResponse,
)

__all__ = [
    "UserCreate",
    "UserLogin",
    "UserResponse",
    "Token",
    "TokenPayload",
    "ForgotPasswordRequest",
    "UserPreferenceResponse",
    "PasswordResetResponse",
    "TokenResponse",
    "SubscriberCreate",
    "SubscriberResponse",
    "InquiryCreate",
    "InquiryResponse",
    "StatsResponse",
    "SessionCreate",
    "SessionResponse",
    "MessageRequest",
    "MessageResponse",
    "TaskExecuteRequest",
    "TaskExecuteResponse",
    "TaskStatusResponse",
]
