import logging
from typing import Optional

from pydantic import BaseModel, Field

logger = logging.getLogger("aivora.agents.insight")


class InsightInput(BaseModel):
    """Input context for the Insight Agent."""
    user_name: str = Field(description="Name of the user")
    upcoming_events_count: int = Field(default=0)
    pending_reminders_count: int = Field(default=0)
    upcoming_trip_destination: Optional[str] = Field(default=None)
    upcoming_trip_days: Optional[int] = Field(default=None)
    weekly_spent: float = Field(default=0.0)
    weekly_limit: float = Field(default=0.0)


class InsightOutput(BaseModel):
    """Output schema representing the AI generated insight."""
    insight_message: str = Field(description="1-2 sentence morning insight generated by the AI.")
    action_suggestion: Optional[str] = Field(default=None)


async def run_insight_agent(input_data: InsightInput) -> InsightOutput:
    """Execute the ADK Insight task workflow to generate a personalized morning briefing."""
    logger.info(f"Running ADK Insight Agent for user: {input_data.user_name}")

    # Generate contextual insight based on user data
    if input_data.upcoming_trip_destination and input_data.upcoming_trip_days is not None:
        if input_data.upcoming_trip_days <= 3:
            msg = f"Your flight to {input_data.upcoming_trip_destination} is in {input_data.upcoming_trip_days} days. I've prepared your packing list and checked the local weather."
        else:
            msg = f"You have an upcoming trip to {input_data.upcoming_trip_destination} in {input_data.upcoming_trip_days} days. Itinerary and bookings are confirmed."
    elif input_data.upcoming_events_count > 0:
        msg = f"You have {input_data.upcoming_events_count} scheduled events today. Your first meeting is ready, and your reminders are prioritized."
    elif input_data.pending_reminders_count > 0:
        msg = f"You have {input_data.pending_reminders_count} pending reminders requiring attention today. Everything else is on track!"
    else:
        msg = "Your schedule is completely clear today! It's a great time to review your goals or log a new activity."

    # Add budget commentary if spent > 80%
    if input_data.weekly_limit > 0 and (input_data.weekly_spent / input_data.weekly_limit) > 0.8:
        msg += f" Note: You're at {int((input_data.weekly_spent / input_data.weekly_limit) * 100)}% of your weekly budget."

    return InsightOutput(
        insight_message=msg,
        action_suggestion="View Full Itinerary" if input_data.upcoming_trip_destination else "View Schedule"
    )
